### PR TITLE
Fix race condition in queued record & document removal

### LINKED ISSUE #266: Race condition in async removal after destroy
With `enqueue: true`, an `after_destroy` callback is added which enqueues a `MeiliSearch::Rails::MSJob` intended to remove the destroyed record from the Meilisearch index:

https://github.com/meilisearch/meilisearch-rails/blob/b9b5efb219c8926551da1caf7566e8d1b2071c9f/lib/meilisearch-rails.rb#L443-L444

https://github.com/meilisearch/meilisearch-rails/blob/b9b5efb219c8926551da1caf7566e8d1b2071c9f/lib/meilisearch-rails.rb#L881-L889

https://github.com/meilisearch/meilisearch-rails/blob/b9b5efb219c8926551da1caf7566e8d1b2071c9f/lib/meilisearch-rails.rb#L367-L384

Line 372 above passes the destroyed record as an argument to the job. Active Job [transparently serializes](https://guides.rubyonrails.org/active_job_basics.html#globalid) the record to a [Global ID](https://github.com/rails/globalid) on enqueue and looks up the record from the Global ID when the job is performed.

The enqueued background job may be performed after the transaction wrapping the record’s destruction has committed. In this case, Active Job won’t be able to find the record in the DB from its Global ID, and the `MSJob` will fail with an `ActiveJob::DeserializationError`.

From a quick look, it seems that the plugin’s tests don’t catch this because they only assert that a job is enqueued with the correct arguments. They might have caught it if they exercised the end-to-end destroy→enqueue→perform flow using `ActiveJob::TestHelper`’s [`perform_enqueued_jobs`](https://github.com/rails/rails/blob/fe8575ed55ab3617339c2623a2993e510381b724/activejob/lib/active_job/test_helper.rb#L598-L627) or similar.

Suggested fix:
1. Replace the `after_destroy` with an `after_destroy_commit` callback.
2. Update the job to take a model and record ID as arguments. (Alternatively, add a new job to avoid breaking changes to the existing background job’s signature.)
3. Attempt to look up the record. If it exists, index it. If it doesn't, delete it from the index.
   ```ruby
   def perform(model, id)
     if record = model.unscoped.find_by(id: id)
       record.ms_index!
     else
       model.ms_remove_document_from_index_by_id!(id)
     end
   end
   ```

Further reading: [`elasticsearch-model`’s documentation](https://github.com/elastic/elasticsearch-rails/tree/main/elasticsearch-model#asynchronous-callbacks) includes an example Sidekiq job implementing an alternative approach (taking an operation name argument rather than using the record’s existence to decide what to do).

History:
* algolia/algoliasearch-rails#75
* algolia/algoliasearch-rails#359
* algolia/algoliasearch-rails#369
* algolia/algoliasearch-rails#422

### PR DESCRIPTION
**Pull request by ellnix**
# Pull Request

## Related issue
Fixes #266

## What does this PR do?

The purpose of this PR is to detach the MeiliSearch document deletion process from the ActiveRecord object so that documents corresponding to a record can be deleted even if the record no longer exists in the database.

Tests were also added for new functionality and to hopefully prevent regressions.

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

## Solution Considerations

Please read #266 for full context:
- The suggested fix in #266 would not work due to the fact that the primary key of a record in an index can be dynamic (by a user-created method) and may not be reconstructed by the record's database ID alone. In addition, a record may have multiple entries in multiple indexes.
- I created a new job so as not to break `MSJob` (although I suspect it would be better if it was replaced with a job dedicated to enqueued indexing, since that's all it does now anyway)
- `ActiveJob` needs to somehow serialize the parameters to a job, default serialization (through `GlobalID`) relies on a database entry to reinitialize the record when the job is run
  - Since the record may no longer exist by the time the job runs, I pass a list of indexes and IDs that _may_ (more on that) belong to the record
- I created a new set of `ms_entries` methods whose purpose is to use the current configuration to list every index the record may have a document in, along with the record's primary key in that index
  - The method does not check `Utilities.indexable?` so it is possible that some of the entries it returns are not actually in MeiliSearch, this is by design since its intention is to be exhaustive and in theory those primary keys _cannot_ belong to another record so deleting them should be ok

### CODE REVIEW

File: lib/meilisearch/rails/ms_clean_up_job.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
+module MeiliSearch
+  module Rails
+    class MSCleanUpJob < ::ActiveJob::Base
+      queue_as :meilisearch
+
+      def perform(documents)
+        documents.each do |document|
+          index = MeiliSearch::Rails.client.index(document[:index_uid])
+
+          if document[:synchronous]
```
Comment (brunoocasali) [inline lib/meilisearch/rails/ms_clean_up_job.rb:10]: Is it helpful to do the check instead of just calling async or sync. But I changed my mind 😅. Let's let the user decide; we don't know the use cases. Maybe it is too much to wait for a call in certain apps, but indispensable for others...

File: spec/ms_clean_up_job_spec.rb [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+  let(:indexes) do
+    %w[SecuredBook BookAuthor Book].map do |uid|
+      Book.index(safe_index_uid uid)
+    end
+  end
+
+  it 'removes record from all indexes' do
+    indexes.each(&:delete_all_documents)
+
+    record
```
Comment (brunoocasali) [inline spec/ms_clean_up_job_spec.rb:26]: I need to say that I think just calling the creation of the AR record like this is weird to me, the line seems lost when I read the whole suite 😅

Comment (brunoocasali) [reply spec/ms_clean_up_job_spec.rb:26]: A `let!` wouldn't do the trick?

**Review by brunoocasali — DISMISSED** [review]
I left a comment but it seems good from my POV.

LGTM!

File: spec/ms_clean_up_job_spec.rb (hunk 2 above)
Comment (ellnix) [reply spec/ms_clean_up_job_spec.rb]: I attempted to refactor it, let me know if I should try again.

**Comment by jeremylynch** [comment]
Would be great to get this one merged! This is causing us some issues.

**Comment by brunoocasali** [comment]
bors merge
