### PR TITLE
Split `spec/integration_spec.rb`

### LINKED ISSUE #358: Race condition in proximity precision test
In the newly added (#351) tests on proximity precision there is a test that fails for me locally but was worked on the CI every time except this one:

https://github.com/meilisearch/meilisearch-rails/actions/runs/9032959217/job/24822189194#step:5:330

Waiting for the last task to finish does not fix it, a `sleep` does. Requires further investigation on how we are updating and fetching settings.

### PR DESCRIPTION
**Pull request by ellnix**
~~Continues after #345: Please only look at commits after "Move Post specs"~~
More changes toward resolving #332

Fixes #358

### CODE REVIEW

File: spec/integration_spec.rb [hunk 1]
```diff
@@ -158,10 +158,6 @@
     expect(Color.search('').size).to eq(1)
   end
 
-  it 'has a Rails env-based index name' do
```
Comment (ellnix) [inline spec/integration_spec.rb:265]: Moved to `configuration_spec.rb`, seemed more appropriate.

File: spec/integration_spec.rb [hunk 2]
```diff
@@ -359,167 +355,6 @@
...
 end
 
-describe 'Book' do
-  before do
-    Book.clear_index!(true)
-    Book.index(safe_index_uid('BookAuthor')).delete_all_documents
-    Book.index(safe_index_uid('Book')).delete_all_documents
-  end
-
-  it 'returns array of tasks on #ms_index!' do
```
Comment (ellnix) [inline spec/integration_spec.rb:514]: Moved to `instance_methods_spec.rb` since it concerns the interface (return type) of one of the instance methods we add to models.

File: spec/integration_spec.rb [hunk 3]
```diff
@@ -359,167 +355,6 @@
...
-    tasks = moby_dick.ms_index!
-
-    expect(tasks).to contain_exactly(
-      a_hash_including('uid'),
-      a_hash_including('taskUid'),
-      a_hash_including('taskUid')
-    )
-  end
-
-  it 'indexes the book in 2 indexes of 3' do
```
Comment (ellnix) [inline spec/integration_spec.rb:526]: Moved to `options_spec.rb` since it tests whether or not the `:if` option is behaving correctly.

File: spec/integration_spec.rb [hunk 4]
```diff
@@ -359,167 +355,6 @@
...
-    expect(results['hits'].length).to eq(1)
-
-    # premium -> not part of the public index
-    index_book = Book.index(safe_index_uid('Book'))
-    expect(index_book).not_to be_nil
-    results = index_book.search('steve')
-    expect(results['hits'].length).to eq(0)
-  end
-
-  it 'sanitizes attributes' do
```
Comment (ellnix) [inline spec/integration_spec.rb:546]: Moved to `options_spec.rb` since it tests whether or not the `:sanitize` option is behaving correctly.

File: spec/integration_spec.rb [hunk 5]
```diff
@@ -359,167 +355,6 @@
...
-    _hack = Book.create! name: '"><img src=x onerror=alert(1)> hack0r',
-                         author: '<script type="text/javascript">alert(1)</script>', premium: true, released: true
-    b = Book.raw_search('hack', { attributes_to_highlight: ['*'] })
-    expect(b['hits'].length).to eq(1)
-    begin
-      expect(b['hits'][0]['name']).to eq('"> hack0r').and_raise(StandardError)
-      expect(b['hits'][0]['author']).to eq('alert(1)')
-      expect(b['hits'][0]['_formatted']['name']).to eq('"> <em>hack</em>0r')
-    rescue StandardError
-      # rails 4.2's sanitizer
```
Comment (ellnix) [inline spec/integration_spec.rb:556]: Kept only the last sanitization format.

File: spec/integration_spec.rb [hunk 6]
```diff
@@ -359,167 +355,6 @@
...
-      rescue StandardError
-        # jruby
-        expect(b['hits'][0]['name']).to eq('"&gt; hack0r')
-        expect(b['hits'][0]['author']).to eq('')
-        expect(b['hits'][0]['_formatted']['name']).to eq('"&gt; <em>hack</em>0r')
-      end
-    end
-  end
-
-  it 'handles removal in an extra index' do
```
Comment (ellnix) [inline spec/integration_spec.rb:570]: Moved to `record_is_updated_spec.rb` since it tests a callback on an event (record being updated)

File: spec/integration_spec.rb [hunk 7]
```diff
@@ -359,167 +355,6 @@
...
-
-    # update the book and make it non-public anymore (not premium, not released)
-    book.update released: false
-
-    # should be removed from the index
-    results = index.search('Public book')
-    expect(results['hits'].size).to eq(0)
-  end
-
-  it 'uses the per_environment option in the additional index as well' do
```
Comment (ellnix) [inline spec/integration_spec.rb:587]: Moved to `configuration_spec.rb`

File: spec/integration_spec.rb [hunk 8]
```diff
@@ -359,167 +355,6 @@
...
-    index = Book.index(safe_index_uid('Book'))
-    expect(index.uid).to eq("#{safe_index_uid('Book')}_#{Rails.env}")
-  end
-
-  it 'searches with one typo min size' do
```
Comment (ellnix) [inline spec/integration_spec.rb:592]: Moved to `settings_spec.rb` since it tests the typo_tolerance setting

File: spec/integration_spec.rb [hunk 9]
```diff
@@ -359,167 +355,6 @@
...
-    Book.create! name: 'Dracula', author: 'me', premium: false, released: true
-    results = Book.search('Darclua')
-    expect(results.size).to eq(0)
-
-    Book.create! name: 'Frankenstein', author: 'me', premium: false, released: true
-    results = Book.search('Farnkenstien')
-    expect(results.size).to eq(1)
-  end
-
-  describe '#ms_entries' do
```
Comment (ellnix) [inline spec/integration_spec.rb:611]: Moved to `instance_methods_spec.rb`

File: spec/integration_spec.rb [hunk 10]
```diff
@@ -112,64 +112,6 @@
   end
 end
 
-describe 'Colors' do
-  before do
-    Color.clear_index!(true)
-    Color.delete_all
-  end
-
-  it 'auto indexes' do
```
Comment (ellnix) [inline spec/integration_spec.rb:193]: Already tested in `options_spec.rb` under `:auto_index`

File: spec/integration_spec.rb [hunk 11]
```diff
@@ -112,64 +112,6 @@
...
-    blue = Color.create!(name: 'blue', short_name: 'b', hex: 0xFF0000)
-    results = Color.search('blue')
-    expect(results.size).to eq(1)
-    expect(results).to include(blue)
-  end
-
-
-  it 'is able to temporarily disable auto-indexing' do
```
Comment (ellnix) [inline spec/integration_spec.rb:216]: Moved to `model_methods_spec.rb`

File: spec/integration_spec.rb [hunk 12]
```diff
@@ -112,64 +112,6 @@
...
-    Color.without_auto_index do
-      Color.create!(name: 'blue', short_name: 'b', hex: 0xFF0000)
-    end
-    expect(Color.search('blue').size).to eq(0)
-    Color.reindex!(MeiliSearch::Rails::IndexSettings::DEFAULT_BATCH_SIZE, true)
-    expect(Color.search('blue').size).to eq(1)
-  end
-
-  it 'updates the index if the attribute changed' do
```
Comment (ellnix) [inline spec/integration_spec.rb:242]: Moved to `record_is_updated_spec.rb`

File: spec/integration_spec.rb [hunk 13]
```diff
@@ -112,64 +112,6 @@
...
-    purple = Color.create!(name: 'purple', short_name: 'p')
-    expect(Color.search('purple').size).to eq(1)
-    expect(Color.search('pink').size).to eq(0)
-    purple.name = 'pink'
-    purple.save
-    expect(Color.search('purple').size).to eq(0)
-    expect(Color.search('pink').size).to eq(1)
-  end
-
-  it 'uses the specified scope' do
```
Comment (ellnix) [inline spec/integration_spec.rb:252]: Moved to `model_methods_spec.rb`

File: spec/integration_spec.rb [hunk 14]
```diff
@@ -112,64 +112,6 @@
...
-    Color.create!(name: 'purple', short_name: 'p')
-    Color.clear_index!(true)
-    Color.where(name: 'red').reindex!(MeiliSearch::Rails::IndexSettings::DEFAULT_BATCH_SIZE, true)
-    expect(Color.search('').size).to eq(3)
-    Color.clear_index!(true)
-    Color.where(id: Color.first.id).reindex!(MeiliSearch::Rails::IndexSettings::DEFAULT_BATCH_SIZE, true)
-    expect(Color.search('').size).to eq(1)
-  end
-
-  it 'indexes an array of documents' do
```
Comment (ellnix) [inline spec/integration_spec.rb:276]: Moved to `model_methods_spec.rb`

File: spec/integration_spec.rb [hunk 15]
```diff
@@ -112,64 +112,6 @@
...
-    json = Color.raw_search('')
-    Color.index_documents Color.limit(1), true # reindex last color, `limit` is incompatible with the reindex! method
-    expect(json['hits'].count).to eq(Color.raw_search('')['hits'].count)
-  end
-
-  it 'does not index non-saved document' do
```
Comment (ellnix) [inline spec/integration_spec.rb:282]: Moved to `instance_method_specs.rb`

File: spec/support/models/color.rb [hunk 16]
```diff
@@ -35,3 +35,10 @@ def will_save_change_to_short_name?
     false
   end
 end
+
+module TestUtil
+  def self.reset_colors!
```
Comment (ellnix) [inline spec/support/models/color.rb:40]: Same rationale as `reset_books!`

File: spec/integration_spec.rb [hunk 17]
```diff
@@ -631,41 +631,6 @@
   end
 end
 
-describe 'Animals' do
-  it 'returns only the requested type' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1044]: Moved to `options_spec.rb` under `(shared index)`

File: spec/integration_spec.rb [hunk 18]
```diff
@@ -631,41 +631,6 @@
...
-    expect(Dog.count).to eq(2)
-    expect(Cat.count).to eq(3)
-
-    expect(Cat.search('felix').size).to eq(1)
-    expect(Cat.search('felix').first.name).to eq('Felix the Cat')
-    expect(Dog.search('toby').size).to eq(1)
-    expect(Dog.search('Toby').first.name).to eq('Toby the Dog')
-  end
-
-  it 'shares a single index' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1057]: Moved to `options_spec.rb`

File: spec/integration_spec.rb [hunk 19]
```diff
@@ -631,41 +631,6 @@
...
-    cat_index = Cat.index.instance_variable_get('@index').uid
-    dog_index = Dog.index.instance_variable_get('@index').uid
-
-    expect(cat_index).to eq(dog_index)
-  end
-
-  describe '#ms_entries' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1064]: Moved to `instance_methods_spec.rb`

File: spec/integration_spec.rb [hunk 20]
```diff
@@ -567,70 +567,6 @@
...
-  before do
-    People.clear_index!(true)
-    People.delete_all
-  end
-
-  before(:all) { MeiliSearch::Rails.configuration[:per_environment] = false }
-
-  after(:all) { MeiliSearch::Rails.configuration[:per_environment] = true }
-
-  it 'adds custom complex attribute' do
```
Comment (ellnix) [inline spec/integration_spec.rb:989]: Moved to `settings_spec.rb`

File: spec/integration_spec.rb [hunk 21]
```diff
@@ -567,70 +567,6 @@
...
-    People.create(first_name: 'Jane', last_name: 'Doe', card_number: 75_801_887)
-    result = People.raw_search('Jane')
-    expect(result['hits'][0]['full_name']).to eq('Jane Doe')
-  end
-
-  it 'has as uid the custom name specified' do
```
Comment (ellnix) [inline spec/integration_spec.rb:995]: Moved to `options_spec.rb`

File: spec/integration_spec.rb [hunk 22]
```diff
@@ -567,70 +567,6 @@
...
-    People.create(first_name: 'Jane', last_name: 'Doe', card_number: 75_801_887)
-    expect(People.index.uid).to eq(safe_index_uid('MyCustomPeople'))
-  end
-
-  it 'has the chosen field as custom primary key' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1000]: Moved to `options_spec.rb`

File: spec/integration_spec.rb [hunk 23]
```diff
@@ -567,70 +567,6 @@
...
-    People.create(first_name: 'Jane', last_name: 'Doe', card_number: 75_801_887)
-    index = MeiliSearch::Rails.client.fetch_index(safe_index_uid('MyCustomPeople'))
-    expect(index.primary_key).to eq('card_number')
-  end
-
-  it 'does not call the API if there has been no attribute change' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1006]: Moved to `record_is_updated_spec.rb`

File: spec/integration_spec.rb [hunk 24]
```diff
@@ -567,70 +567,6 @@
...
-    People.create(first_name: 'Jane', last_name: 'Doe', card_number: 75_801_887)
-
-    person = People.search('Jane').first
-
-    expect do
-      person.update(first_name: 'Jane')
-    end.not_to change(People.index.tasks['results'], :size)
-  end
-
-  it 'does not auto-remove' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1016]: Moved to `options_spec.rb`

File: spec/integration_spec.rb [hunk 25]
```diff
@@ -567,70 +567,6 @@
...
-    People.create(first_name: 'Joanna', last_name: 'Banana', card_number: 75_801_888)
-    joanna = People.search('Joanna')[0]
-    joanna.destroy
-    result = People.raw_search('Joanna')
-    expect(result['hits'].size).to eq(1)
-  end
-
-  it 'is able to remove manually' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1024]: Moved to `instance_methods_spec.rb`

File: spec/integration_spec.rb [hunk 26]
```diff
@@ -567,70 +567,6 @@
...
-    bob = People.create(first_name: 'Bob', last_name: 'Sponge', card_number: 75_801_889)
-    result = People.raw_search('Bob')
-    expect(result['hits'].size).to eq(1)
-    bob.remove_from_index!
-    result = People.raw_search('Bob')
-    expect(result['hits'].size).to eq(0)
-  end
-
-  it 'clears index manually' do
```
Comment (ellnix) [inline spec/integration_spec.rb:1033]: Moved to `model_methods_spec.rb`

File: spec/system/tech_shop_spec.rb
Comment (ellnix) [inline spec/system/tech_shop_spec.rb:1]: Forgot to mention in the commit, but is me adding another layer of tests (system tests).

We would have
- Unit tests
- Integration tests (checking that systems fit together gives simple scenarios)
- System tests (do common tasks with a setup of realistic data)
- Acceptance tests (reserved for full-stack tests, i. e. running a rails app and testing it with selenium verify with 100% certainty that a small subset of setups that we lay out work. Could also be helpful in letting us see what needs to be updated on a user's end when we make changes)

File: spec/system/tech_shop_spec.rb [hunk 27]
```diff
@@ -1,8 +1,10 @@
+require 'support/async_helper'
 require 'support/models/product'
 
 describe 'Tech shop' do
   before(:all) do
-    Product.clear_index!(true)
```
Comment (ellnix) [inline spec/system/tech_shop_spec.rb]: Funnily enough, this never worked! Product has indexing disabled and in cases where indexing is disabled clear_index does nothing.

However, this did not present an issue since this one describe block was the only thing using product. When this runs after the recently-added multi search specs where I also used product, many of the expectations fail :rofl: 

I found out the hard way as you can imagine.

File: spec/system/tech_shop_spec.rb [hunk 28]
```diff
@@ -37,150 +39,142 @@
     # Subproducts
     @camera = Camera.create!(name: 'canon eos rebel t3', href: 'canon')
 
-    100.times { Product.create!(name: 'crapoola', href: 'crappy', tags: ['crappy']) }
```
Comment (ellnix) [inline spec/system/tech_shop_spec.rb]: This alone removed over half a second from the test runtime for me. These 100 "crapoola"s are actually used in the specs.

File: spec/system/tech_shop_spec.rb [hunk 29]
```diff
@@ -37,150 +39,142 @@
...
-
-    @products_in_database = Product.all
```
Comment (ellnix) [inline spec/system/tech_shop_spec.rb]: This should probably save on memory, but the biggest difference it'll probably make is removing a line of code that we never needed.

File: spec/system/tech_shop_spec.rb [hunk 30]
```diff
@@ -37,150 +39,142 @@
...
-    expect(results_before_clearing['hits'].size).to be(results_after_reindexing['hits'].size)
+    it 'supports manual indexing' do
+      products_before_clear = Product.raw_search('')['hits']
+      expect(products_before_clear).not_to be_empty
+
+      Product.clear_index!(true)
+
+      products_after_clear = Product.raw_search('')['hits']
+      expect(products_after_clear).to be_empty
+      Product.reindex!(MeiliSearch::Rails::IndexSettings::DEFAULT_BATCH_SIZE, true)
```
Comment (ellnix) [inline spec/system/tech_shop_spec.rb:60]: This syntax is still clunky but I'm saving it for when I refactor the actual lib, not the test suite.

File: spec/system/tech_shop_spec.rb [hunk 31]
```diff
@@ -37,150 +39,142 @@
...
                              description: 'Big screen')
 
       ipad.index!(true)
       results = Product.search('ipad')
-      expect(results.size).to eq(1)
+      expect(results).to contain_exactly(ipad)
 
       ipad.destroy
-      results = Product.search('ipad')
-      expect(results.size).to eq(0)
```
Comment (ellnix) [inline spec/system/tech_shop_spec.rb]: Fun fact: this actually tested nothing.

As one of the later tests asserts, if there is a document in the ms index that cannot be found in AR, it won't be returned by `search` (although it is returned by `raw_search`).

This is why this never caused any errors despite the obvious-looking race condition between this assertion and the above `ipad.destroy` line.

File: spec/system/tech_shop_spec.rb [hunk 32]
```diff
@@ -37,150 +39,142 @@
...
         Product.index.add_documents!(@palmpre.attributes.merge(id: -1))
-        expect { Product.search('pal').to_json }.not_to raise_error
+        expect { Product.search('pal') }.not_to raise_error
         Product.index.delete_document!(-1)
       end
 
-      it 'returns the other results if those are still available locally' do
+      it 'returns other available results' do
         Product.index.add_documents!(@palmpre.attributes.merge(id: -1))
-        expect(JSON.parse(Product.search('pal').to_json).size).to eq(2)
```
Comment (ellnix) [inline spec/system/tech_shop_spec.rb]: I do not understand why this was being converted to `json` and back. If there's some edge case or special significance to this please let me know.

**Comment by ellnix** [comment]
@brunoocasali I tried to keep the commits as small as possible, and annotated a lot of the earlier ones. I would recommend going through this **commit by commit** rather than through `Files changed`.

**Review by brunoocasali — APPROVED** [review]
LGTM!

bors merge
