### PR TITLE
Fix settings update regression

### LINKED ISSUE #280: Skip indexCreation and settingsUpdate whenever adding new record in production
Whenever calling ms_index!, I noticed there will always be 3 tasks occurring which might not be necessary and may even be detrimental to million records indexes.

```
# uid: indexUid - status / type
78571: Movie - succeeded / documentAdditionOrUpdate
78570: Movie - succeeded / settingsUpdate (===> Takes a long time to finish depending on million records)
78569: Movie - failed / indexCreation
```

It appear that indexCreation will always failed, then settingsUpdate will always take a long time (depending on how many records you have).

Is there a way to not do indexCreation + settingsUpdate and just do documentAdditionOrUpdate in a more intelligent manner?

And let us do settingsUpdate manually at least in production mode where it seldom changes.

### LINKED ISSUE #328: Index not created since 0.11.0 - 404 Not Found
Ever since upgrading from Meilisearch 0.10.2 to 0.11.0 we are getting multiple errors in our test suite: 

```
MeiliSearch::ApiError: 404 Not Found - Index `Cars_test` not found.
```

We are using Minitest/FactoryBot for testing. 

Is there anything we need to do to ensure these indexes are created?

### LINKED ISSUE #329: Upgrading to 0.11.0 produces "The request was not processed in the expected time." repeatedly.
After upgrading to 0.11.0, I got blasted with this error on every mutation on my model.

```
The request was not processed in the expected time.

meilisearch-0.26.0/lib/meilisearch/task.rb:49:in `rescue in wait_for_task'
meilisearch-0.26.0/lib/meilisearch/task.rb:39:in `wait_for_task'
meilisearch-0.26.0/lib/meilisearch/client.rb:143:in `wait_for_task'
meilisearch-0.26.0/lib/meilisearch/client.rb:45:in `create_index!'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:264:in `block in initialize'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:316:in `log_or_throw'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:263:in `initialize'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:770:in `new'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:770:in `ms_ensure_init'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:548:in `block in ms_index!'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:544:in `each'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:544:in `map'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:544:in `ms_index!'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:928:in `ms_index!'
```

I must say due to the excessive indexing settings, I did mute it previously on my settings like so:

```ruby
meilisearch check_settings: false do
  # my indexing settings...
end
```

Not sure if this will interfere with the current version though.

### PR DESCRIPTION
**Pull request by ellnix**
# Pull Request

## Related issue
Fixes #329
May fix #328

## What does this PR do?
- `SafeIndex` before I tried to fix #280 with #301 did not guarantee that its index exists at all, since `@index` was created asynchronously it was possible that `SafeIndex#settings` could be called on an index that does not exist.
  This line:
  https://github.com/meilisearch/meilisearch-rails/blob/29f59c88881b5a4b5a03d990f11d3aac220cd367/lib/meilisearch-rails.rb#L309 
  was supposed return an empty hash when asked to fetch the settings of an index that does not exist, however `ApiError#code` is the meilisearch code (`"index_not_found"`) and not the http code (`404`). That line was therefore skipped and the `index_not_found` error was being propagated and caught by the `rescue nil` in:
  https://github.com/meilisearch/meilisearch-rails/blob/e5ad4d1f10c078097bf211e4d3a6e1d48b24bbc5/lib/meilisearch-rails.rb#L750
  until I removed it and tried to replace it with ensuring that `SafeIndex` had an index by making `create_index!` synchronous and all kinds of hell broke loose since now every time an index was used would cause a synchronous wait.

### CODE REVIEW

File: lib/meilisearch-rails.rb [hunk 1]
```diff
@@ -843,7 +843,7 @@ def meilisearch_settings_changed?(server_state, user_configuration)
           if user.is_a?(Hash) && server.is_a?(Hash)
             meilisearch_settings_changed?(server, user)
           elsif user.is_a?(Array) && server.is_a?(Array)
-            user.map(&:to_s) != server.map(&:to_s)
+            user.map(&:to_s).sort! != server.map(&:to_s).sort!
```
Comment (brunoocasali) [inline lib/meilisearch-rails.rb:846]: Why did you have to use `sort!` and not just `sort` here?

File: lib/meilisearch-rails.rb [hunk 2]
```diff
@@ -261,7 +261,7 @@ def initialize(index_uid, raise_on_failure, options)
         @raise_on_failure = raise_on_failure.nil? || raise_on_failure
 
         SafeIndex.log_or_throw(nil, @raise_on_failure) do
-          client.create_index!(index_uid, { primary_key: primary_key })
+          client.create_index(index_uid, { primary_key: primary_key })
```
Comment (brunoocasali) [inline lib/meilisearch-rails.rb:264]: Let's trust on the test suite 🙏

File: lib/meilisearch-rails.rb [hunk 3]
```diff
@@ -306,7 +306,7 @@ def settings(*args)
         SafeIndex.log_or_throw(:settings, @raise_on_failure) do
           @index.settings(*args)
         rescue ::MeiliSearch::ApiError => e
-          return {} if e.code == 404 # not fatal
+          return {} if e.code == 'index_not_found' # not fatal
```
Comment (brunoocasali) [inline lib/meilisearch-rails.rb:309]: I'm not sure why we had the 404 in the first place, but `index_not_found` is just one issue that could happen, shouldn't we make it more generic? Like parsing the error response to grab a "match-all" case?

Comment (brunoocasali) [inline lib/meilisearch-rails.rb:309]: I'm not sure why we had the 404 in the first place, but `index_not_found` is just one issue that could happen, shouldn't we make it more generic? Like parsing the error response to grab a "match-all" case?

**Review by brunoocasali — APPROVED** [review]
@ellnix I made some points that we could discuss, but I don't think we should wait for the answers.

LGTM!

File: lib/meilisearch-rails.rb (hunk 1 above)
Comment (ellnix) [reply lib/meilisearch-rails.rb:846]: Mainly out of frustration. While I understand objectively that this function is very short and does not deal with a lot of data, the type conversions really bother me and it feels like it performs terribly.

So I looked up performance comparisons for different methods to compare arrays regardless of order and `sort!` was slightly faster than `sort`.

Of course these arrays are tiny and the difference does not matter one bit, especially since `map` already crates new arrays.

File: lib/meilisearch-rails.rb (hunk 3 above)
Comment (ellnix) [reply lib/meilisearch-rails.rb:309]: I think the logic is that everytime an index is used, we attempt to create it __and__ we also check if its settings are good, immediately afterward.

So
- if `index.settings` says that the index is not found
- it means that the index has just been created
- thus we can pass `{}` as the settings to compare against the user settings
- this way if there are any user settings at all (we know the index has just been created) we will send an `update_settings` request

This logic has a flaw that we should discuss in due time but it's minor.

Anyway from what I can see the only purpose of this rescue block is to handle this one case wherein the index has not been created yet. Other errors are handled by `log_or_throw` since this method just propagates them.

**Comment by ellnix** [comment]
bors merge
